### ISSUE TITLE
admin panel backend links connect to frontend and test

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#180]

**Comment by Pooja-Lohar25** [comment]
If the issue still persists, please describe it properly I would like to work on it and contribute.

**Comment by rohitagr0310** [comment]
we want to connect the admin panel backend functions that are inside the function folders, we wish to connect the functions to frontend, but it would require connect with the database, we have a local database whose connection is in the db-test.js

the sample local database has not been shared yet. after it is shared, you can setup .env file and provide the connection and run the backend development server

I will provide the database as fast as I can
