### ISSUE TITLE
enhance footer UI

### ISSUE THREAD

**Issue by Gobinath-B** [rohitagr0310/Bookflow-app#219]
The footer of the application was not seems good. I want to enhance the design

**Comment by ashishk1331** [comment]
What exactly you have on your mind? 
Here are few examples,
https://www.figma.com/file/fwCHY2BGLX8akiIQIWLbYT?type=design

**Comment by rohitagr0310** [comment]
@Gobinath-B Do you wish to work on new design for the footer. If so , I will assign the issue to you

**Comment by ashishk1331** [comment]
If it's necessary. I've mistaken @Gobinath-B to be the maintainer and so I responded to the issue. To change the footer for jo reason specific isn't worth it. 🤔 

However, if you want to then I can do it.

**Comment by rohitagr0310** [comment]
@ashishk1331 you can work on this , if you wish to but there are no particular new features to add in the footer, I can only be redesigned or its design can be improved.

However if you wish to add new features in the footer, you are welcome to do so

**Comment by rohitagr0310** [comment]
i have assigned the issue to you.

work on a new branch with the feature as the branch name

when you create a pull request, request review from @jain-anshika or @jayesh2474

**Comment by ashishk1331** [comment]
One more thing, There is this empty space at the bottom. An extra section at the bottom is causing it.
Should I also eliminate the sapce? 

Developer tools inspection,
![image](https://github.com/rohitagr0310/Bookflow-app/assets/44055846/a900dcf4-ed2f-48bd-be6d-647b512f65cf)

UI error,
![image](https://github.com/rohitagr0310/Bookflow-app/assets/44055846/d58a2f1b-7e3e-4436-88e4-fcdcad16061e)

**Comment by Gobinath-B** [comment]
> @Gobinath-B Do you wish to work on new design for the footer. If so , I will assign the issue to you

yeah ,sure. I'm enthusiastic to work on this.

**Comment by rohitagr0310** [comment]
yes, please remove the white space

**Comment by ashishk1331** [comment]
Okay I'll do it.

**Comment by ashishk1331** [comment]
> One more thing, There is this empty space at the bottom. An extra section at the bottom is causing it. Should I also eliminate the sapce?
> 
> Developer tools inspection, ![image](https://user-images.githubusercontent.com/44055846/272226879-a900dcf4-ed2f-48bd-be6d-647b512f65cf.png)
> 
> UI error, ![image](https://user-images.githubusercontent.com/44055846/272227176-d58a2f1b-7e3e-4436-88e4-fcdcad16061e.png)

I'm deeply sorry that the white space was caused by an extension I've been running in my browser. In reality, the app doesn't have any trailing white sections.

**Comment by ashishk1331** [comment]
I think I'm hijacking this issue from @Gobinath-B. So, If you want to handle this issue please go ahead. Else, I'll try my best here.

**Comment by Gobinath-B** [comment]
@ashishk1331 I'm currently working on this issue, thanks man.

**Comment by jain-anshika** [comment]
Since the PR has been merged I will close the issue.
Thank you for you contribution!!
