### ISSUE TITLE
Whole UI

### ISSUE THREAD

**Issue by shrey802** [rohitagr0310/Bookflow-app#221]
I feel the UI is poor I can help you style it !! Can you assign this to me under hacktoberfest?

**Comment by rohitagr0310** [comment]
Sure, Have a great Hacktoberfest

**Comment by shrey802** [comment]
thanks will start working on it!!

**Comment by jain-anshika** [comment]
@shrey802 
What is the update? Please share the screenshots of the changes made.

**Comment by shrey802** [comment]
yes working on it sending screenshots in sometime

**Comment by rohitagr0310** [comment]
@shrey802
What is the update? Please share the screenshots of the changes made.
