### ISSUE TITLE
Unrestricted access allowed to Student and Admin paths

### ISSUE THREAD

**Issue by vmittal05** [rohitagr0310/Bookflow-app#222]
Hi, Currently any user without logging in can directly access the admin and user dashboards. I will implement protected routes to restrict access to these routes and redirect the user to login page if the user tries to directly access these pages.

![image](https://github.com/rohitagr0310/Bookflow-app/assets/41340985/da132e1f-0b59-40a3-af5c-50ec54347f89)

**Comment by rohitagr0310** [comment]
@vmittal05 That would be a great feature. I would love to work on that with you

**Comment by vmittal05** [comment]
@rohitagr0310 , I am thinking of adding a Authenticator component wrapper for the route which will check for the login status before rendering the protected component.
If you have any other idea or suggestions, let me know and I can start working on it.

**Comment by rohitagr0310** [comment]
as of currently, when the user logins, its id and userType (A for admin and U for user) gets stored in localstorage

if we use Authenticator component wrapper, will it be able to work with that backend

**Comment by vmittal05** [comment]
Yes, in the Authenticator component will check for this particular userType in local storage and allow access based on that, so there will be no dependency on the backend.

**Comment by rohitagr0310** [comment]
Then that would be great

**Comment by rohitagr0310** [comment]
Then that would be great

**Comment by jain-anshika** [comment]
@vmittal05 
What is the update? Please share the screenshots of the changes made.

**Comment by vmittal05** [comment]
@jain-anshika, I have added a new Auth component for the protected routes:
![image](https://github.com/rohitagr0310/Bookflow-app/assets/41340985/9a4fb7f7-3fe0-4692-84ec-692631a2441b)

Also, if the user tries to go to a non-existent path, he will be redirected to home page.
![image](https://github.com/rohitagr0310/Bookflow-app/assets/41340985/2f70ee91-45a8-41d3-9473-fcf2239e8b62)

Let me know if you have any suggestions, if it is fine will raise a PR to merge the changes.

**Comment by jain-anshika** [comment]
@vmittal05 
Looks great!! Raise the PR.

**Comment by vmittal05** [comment]
Hi @rohitagr0310, I have resolved the build issues, let me know if you still wish to take this up, I can raise the PR right away.

**Comment by rohitagr0310** [comment]
please raise the pr

**Comment by vmittal05** [comment]
Sure, will raise a new PR shortly
