### ISSUE TITLE
 Implement Lazy Loading with Loader

### ISSUE THREAD

**Issue by M-A-N-I-K** [rohitagr0310/Bookflow-app#223]
To address this issue and enhance the user experience, I propose implementing lazy loading for images and other resources. Lazy loading will delay the loading of non-essential content until it's needed, reducing initial load times. Additionally, we'll incorporate a loader to provide visual feedback to users while content is being loaded.

**Comment by qaidjoharj53** [comment]
@M-A-N-I-K Okay you can implement the feature in a new branch and it will be reviewed then.

All the Best !

**Comment by rohitagr0310** [comment]
The issue is complete and the pr has been merged

Thank you for your contribution
