### ISSUE TITLE
Enhance the ui of login and sign up form.

### ISSUE THREAD

**Issue by Aarav238** [rohitagr0310/Bookflow-app#225]
I would like to work on enhancing the ui of login and sign up form.
Please assign this issue to me.

**Comment by rohitagr0310** [comment]
i have assigned the issue to you.

work on a new branch with the feature as the branch name 

when you create a pull request, request review from @jain-anshika or @jayesh2474

**Comment by jain-anshika** [comment]
@Aarav238 
What is the update? Please share the screenshots of the changes made.

**Comment by jain-anshika** [comment]
#262

**Comment by Aarav238** [comment]
@jain-anshika I will push the changes by tomorrow
