### ISSUE TITLE
Text visibility is bad in testimonials section. Need to change the text color. 

### ISSUE THREAD

**Issue by RoastedBrotato** [rohitagr0310/Bookflow-app#226]

**Comment by qaidjoharj53** [comment]
@RoastedBrotato We would like to collaborate with you.
Can you please elaborate how and what all stylings you will apply and improve?

**Comment by RoastedBrotato** [comment]
> @RoastedBrotato We would like to collaborate with you. Can you please elaborate how and what all stylings you will apply and improve?

I look forward to it!

I could change the text color and add styles so that when the text is not hovered, the text appears white, but when it's hovered, it appears to the color you have set right now.

**Comment by rohitagr0310** [comment]
i have assigned the issue to you.

work on a new branch with the feature as the branch name

when you create a pull request, request review from @jain-anshika or @jayesh2474
