### ISSUE TITLE
(refactor): Home Page

### ISSUE THREAD

**Issue by aayu5hgit** [rohitagr0310/Bookflow-app#233]
The current (live) home page of the application looks not-so-engaging from a user's POV.

Things to be added:
- [ ] Fixing Navbar 
- [ ] Adding a Carousel
- [x] Testimonial re-design
- [x] Details to be displayed in a systematic manner
- [ ] Footer should take minimum space

I would like you to give me the opportunity to fix this and get a pretty well designed and engaged `home page`

**Comment by rohitagr0310** [comment]
Yes, you can work on this

i have assigned the issue to you.

work on a new branch with the feature as the branch name

when you create a pull request, request review from @jain-anshika or @jayesh2474

**Comment by jain-anshika** [comment]
@aayu5hgit 
What is the update? Please share the screenshots of the changes made.

**Comment by dipanshparmar** [comment]
If this issue gets unassigned in the near future, I would love to take this.

**Comment by aayu5hgit** [comment]
@jain-anshika I'll push the changes in a few and raise a PR

**Comment by aayu5hgit** [comment]
@dipanshparmar If you are wiling to give a try, you can work on `footer`

**Comment by dipanshparmar** [comment]
Sure! Once you raise the PR, I'll create a new issue for this if required.

**Comment by aayu5hgit** [comment]
@jain-anshika Can I install tailwindCSS?

**Comment by dipanshparmar** [comment]
I guess you are mistaking me as a collaborator here.

**Comment by aayu5hgit** [comment]
@dipanshparmar haha, sorry for the wrong mention

**Comment by aayu5hgit** [comment]
@dipanshparmar you can start contributing for the above mentioned tasks
I am having a busy schedule today, won't be able to contribute with a focus here.
All the best!

**Comment by dipanshparmar** [comment]
Thanks @aayu5hgit.

@rohitagr0310 Can you please update the assignees?

**Comment by rohitagr0310** [comment]
@dipanshparmar 
What is the update? Please share the screenshots of the changes made.

**Comment by dipanshparmar** [comment]
I have the design ready but haven't been able to implement that yet. I'll push the changes in one to two days.

**Comment by dipanshparmar** [comment]
I've completed most of the UI. Just need to work on the header, some refinements here and there, and responsiveness. I'll push the code tomorrow by midnight.

**Comment by dipanshparmar** [comment]
@rohitagr0310 Which branch should I make the merge request to?

**Comment by rohitagr0310** [comment]
@dipanshparmar develop branch
