### ISSUE TITLE
auth problem. Can't sign up

### ISSUE THREAD

**Issue by shrey802** [rohitagr0310/Bookflow-app#235]
![hacktober](https://github.com/rohitagr0310/Bookflow-app/assets/55155180/7d43f3e4-860e-4e87-8506-3d8a8add1fd8)

**Comment by rohitagr0310** [comment]
this problem occurs as the login function is not able to connect to the database. you will need to create a .env file with database credentials . sample database will be provided then the login and signup functionality will start working.

**Comment by rohitagr0310** [comment]
as of now, i have opened the admin panel and student panel for development purposes. 

the can be accessed by adding `/admin` and `/student' in the base url
