### ISSUE TITLE
(fix): Fix the husky implementation 

### ISSUE THREAD

**Issue by hrit1997** [rohitagr0310/Bookflow-app#238]

**Comment by rohitagr0310** [comment]
there has been a problem with husky pipeline and I would appreciate it if you fix it

**Comment by rohitagr0310** [comment]
i have assigned the issue to you.

work on a new branch with the feature as the branch name

when you create a pull request, request review from @jain-anshika or @jayesh2474

**Comment by jain-anshika** [comment]
@hrit1997 
What is the update? Please share the screenshots of the changes made. 
@rohitagr0310
