### ISSUE TITLE
Improve 'Terms and Conditions' page

### ISSUE THREAD

**Issue by vinayakjaas** [rohitagr0310/Bookflow-app#240]
I would like to propose an assignment to improve our 'Terms and Conditions' page for the BookFlow web application With Better UI . This is an important aspect of your service, and I believe that enhancing this document can benefit both our users and the company
So, Please Assign this task to me I try to a better UI and and rewrite Terms and condition with proper Structure.
![image](https://github.com/rohitagr0310/Bookflow-app/assets/96948435/563cdc01-02fe-46dc-b9ed-28a5a8bfe6ec)

**Comment by jain-anshika** [comment]
Go Ahead!! I have assigned the issue to you @vinayakjaas .

Work on a new branch with the feature as the branch name.
Also add screenshots after making changes.

When you create a pull request, request review from  @rohitagr0310 , @jain-anshika  or @qaidjoharj53

**Comment by vinayakjaas** [comment]
@jain-anshika @rohitagr0310   please review my PR

**Comment by rohitagr0310** [comment]
The issue is complete and the pr has been merged

Thank you for your contribution
