### ISSUE TITLE
Improve TESTIMONIALS 

### ISSUE THREAD

**Issue by vinayakjaas** [rohitagr0310/Bookflow-app#241]
Text Written in TESTIMONIALS is not clearly visible unless we hover over the text area. I want to improve this I am trying to make the TESTIMONIALS section very stylish and responsive with text clearly visible so Please assign this task to me.
![image](https://github.com/rohitagr0310/Bookflow-app/assets/96948435/ec2dd34c-e156-4d22-b019-cc175b93a2d6)

**Comment by jain-anshika** [comment]
Go Ahead! I have assigned the issue to you @vinayakjaas .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from  @rohitagr0310 , @jain-anshika  or , @qaidjoharj53

**Comment by Pratikdate** [comment]
Can you also add me for this assignment.

**Comment by jain-anshika** [comment]
@vinayakjaas 
What is the update? Please share the screenshots of the changes made.

**Comment by Pratikdate** [comment]
Assigned me I will work on it

**Comment by vinayakjaas** [comment]
@jain-anshika Please review My Pr
