### ISSUE TITLE
Improve the fonts and favicon.ico

### ISSUE THREAD

**Issue by kayceenuel** [rohitagr0310/Bookflow-app#244]
### **Can** I work on this?

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @kayceeNuel .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by aparna03dubey** [comment]
@rohitagr0310 @jain-anshika  @qaidjoharj53  It would be great if you assign me this issue for hacktober fest.

**Comment by rohitagr0310** [comment]
@aparna03dubey I am sorry, but the issue has already been assigned, if the issue is not complete and becomes inactive, only then will we reassign it

Thank you

**Comment by kayceenuel** [comment]
> Go Ahead! I have assigned the issue to you @kayceeNuel .
> 
> Work on a new branch with the feature as the branch name.
> 
> When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

Alright then.

**Comment by jain-anshika** [comment]
#254 
@kayceeNuel 
who ever creates a PR first will be merged and other will be closed as not planned.
