### ISSUE TITLE
Alignment issue in Footer.

### ISSUE THREAD

**Issue by Vatsalmadhur** [rohitagr0310/Bookflow-app#246]
The various links such as Home About Contact etc are aligned vertically. This would look better is aligned in  a horizontal manner.
![Screenshot 2023-10-04 at 11 28 08 AM](https://github.com/rohitagr0310/Bookflow-app/assets/107473447/3cfd32cd-8bd9-4349-9466-082f55f810b2)

**Comment by Vatsalmadhur** [comment]
I request you to assign me this issue

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Vatsalmadhur .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by Vatsalmadhur** [comment]
I have made a PR #255 . I request @rohitagr0310 and others to review my PR.

**Comment by rohitagr0310** [comment]
The issue is complete and the pr has been merged

Thank you for your contribution
