### ISSUE TITLE
Width of content.

### ISSUE THREAD

**Issue by Vatsalmadhur** [rohitagr0310/Bookflow-app#247]
The width of the content in the home page is greater than what it should ideally be. I will make the content 's width more central such that it looks good and is easy to read.
![Screenshot 2023-10-04 at 11 28 22 AM](https://github.com/rohitagr0310/Bookflow-app/assets/107473447/f1e8a113-af4d-4e93-8d8b-321e8103a895)

**Comment by Vatsalmadhur** [comment]
I request you to assign me this issue.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Vatsalmadhur .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by Vatsalmadhur** [comment]
Please have a look at PR #266. Review requested @rohitagr0310 and others.
