### ISSUE TITLE
forget password ui update

### ISSUE THREAD

**Issue by naveen1m** [rohitagr0310/Bookflow-app#253]
![image](https://github.com/rohitagr0310/Bookflow-app/assets/94122792/c4387c36-f768-4578-978b-a602e43a8934)

**Comment by naveen1m** [comment]
assign me this work for hacktoberfest

**Comment by jain-anshika** [comment]
Go Ahead! I have assigned the issue to you @stupiddint  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310  , @jain-anshika  or , @qaidjoharj53
