### ISSUE TITLE
Add: favicon for bookFlow website

### ISSUE THREAD

**Issue by naveen1m** [rohitagr0310/Bookflow-app#254]
assign me this for hacktoberfest

**Comment by jain-anshika** [comment]
Explain what you want to do?

**Comment by anshulkumarx7** [comment]
Can you please assign me this??

**Comment by jain-anshika** [comment]
@stupiddint
Explain how you propose to do this?

**Comment by anshulkumarx7** [comment]
I WILL BE SEARCHING THE BEST LOGO THAT FITS BEST WITH YOUR WEBSITE AND IT AS FAVICON INSTEAD OF REACT.JSC FAVICON

**Comment by jain-anshika** [comment]
#244 
@anshulkumarx7 
who ever creates a PR first will be merged and other will be closed as not planned.

**Comment by rohitagr0310** [comment]
@shrey802
What is the update? Please share the screenshots of the changes made.
