### ISSUE TITLE
Default META Tags

### ISSUE THREAD

**Issue by abhayst007** [rohitagr0310/Bookflow-app#256]
![image](https://github.com/rohitagr0310/Bookflow-app/assets/75574622/80fbe602-e296-413b-b205-80dd087f80c3)
![image](https://github.com/rohitagr0310/Bookflow-app/assets/75574622/5ade9474-120b-49dd-8a6c-89d84b4eb611)
The link preview or embed is default

**Comment by abhayst007** [comment]
It is an easy fix I can create a PR

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @abhayst007  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 or @qaidjoharj53 or @jain-anshika .

**Comment by abhayst007** [comment]
I need content for meta tags
Title
Description 
Image

I can change the favicon also so It would be great if you provide favicon file

**Comment by abhayst007** [comment]
Good Evening
Can I get the following so I can implement the meta tags

> I need content for meta tags Title Description Image
> 
> I can change the favicon also so It would be great if you provide favicon file

**Comment by abhayst007** [comment]
Hello @qaidjoharj53 can I get the following things please


> I need content for meta tags Title Description Image
> 
> I can change the favicon also so It would be great if you provide favicon file

**Comment by abhayst007** [comment]
It's been 3 days I still got no reply @qaidjoharj53 @rohitagr0310 @jain-anshika

**Comment by rohitagr0310** [comment]
it is an open source proje
