### ISSUE TITLE
Create a Contributing.md file

### ISSUE THREAD

**Issue by kaustab28** [rohitagr0310/Bookflow-app#257]
It seems that the project doesn't contain a contributing.md file. Having that file would be really helpful for beginners to know how to contribute to the project.

The repository requires general instructions about how people can contribute to this project.
General instruction:
_How to set up the project.
How they can communicate through issues.
How to create pull requests etc._

Could you please assign this issue to me under Hacktoberfest?

**Comment by maida12** [comment]
can i do this?

**Comment by jain-anshika** [comment]
Go Ahead! I have assigned the issue to you @kaustab28  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by kaustab28** [comment]
Got it!!
Thanks.

**Comment by kaustab28** [comment]
Issues can be self-assigned?! How does this work?
