### ISSUE TITLE
Fix: User Validation in Password Reset Process.

### ISSUE THREAD

**Issue by satvik225** [rohitagr0310/Bookflow-app#260]
At present, there is no validation check in place when resetting a password to verify whether the user exists in the database or not.

To improve this, we should implement a validation check when the user clicks on the "Reset Password" button. This check will verify whether the user exists in the database. If the user is not found, a pop-up message will be displayed, saying "No such email exists. Please sign up on our website." This message will also include a button that, when clicked, will redirect the user to the signup page.

**Comment by satvik225** [comment]
I would like to work on this issue, if it's approved.

**Comment by jain-anshika** [comment]
@satvik225 
How do you propose to do this?

**Comment by satvik225** [comment]
@jain-anshika  
When the user clicks the "Reset Password" button, an API request will be initiated to determine whether the user exists in the database. If the API call response confirms the user's existence (i.e., returns true), they will be redirected to the password reset page. However, if the API response indicates that the user is not found(i.e., returns false), a popup message will be displayed stating above mentioned message.

**Comment by satvik225** [comment]
> @satvik225 How do you propose to do this?

@jain-anshika
Would it be helpful if I provided more details?
