### ISSUE TITLE
Not responsive and Lack of padding

### ISSUE THREAD

**Issue by abhayst007** [rohitagr0310/Bookflow-app#261]
![image](https://github.com/rohitagr0310/Bookflow-app/assets/75574622/f49aad1c-8b48-4d7f-8bc8-48cda883628e)
There is overflow by which some portion of text stays hidden.
![image](https://github.com/rohitagr0310/Bookflow-app/assets/75574622/f8663893-2e40-45b2-8c68-d17de1dfcc2a)
Due to lack of padding the UI doesn't look uniform.

**Comment by jain-anshika** [comment]
Go Ahead! I have assigned the issue to you @abhayst007  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
