### ISSUE TITLE
(BUG)- Auth page

### ISSUE THREAD

**Issue by jain-anshika** [rohitagr0310/Bookflow-app#262]
The SignIn page is not looking good because of this white background-
![image](https://github.com/rohitagr0310/Bookflow-app/assets/115166105/d65abb09-613a-4b93-a83e-0249dcfc35ed)

The SignUp page is not looking good because of this white background-
![image](https://github.com/rohitagr0310/Bookflow-app/assets/115166105/fa26f3b4-bbeb-4831-86d1-81825a338184)

**Comment by jain-anshika** [comment]
#225

**Comment by kshitij-0711** [comment]
Hi @jain-anshika , would you mind assigning this issue to me?

**Comment by yash7xm** [comment]
I will do it assign this to  me
