### ISSUE TITLE
Fonts and text alignment

### ISSUE THREAD

**Issue by HarshProj** [rohitagr0310/Bookflow-app#279]
Want to use another font and to add type writter effect in home page heading 
 
 Please assign this issue to me.

**Comment by rohitagr0310** [comment]
@HarshProj 
we belive the ui for homepage is already good and we do not wish to bring any changes in it. if you wish to improve the UI, can you help in the admin panel and student panel.

they can be accessed by the adding /student and /admin in the base url

**Comment by rohitagr0310** [comment]
if you wish to work on that, then I can assign this issue to you

**Comment by HarshProj** [comment]
Ok I'll work on it

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @HarshProj .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
