### ISSUE TITLE
Add header to reset password page and link tag to logo in footer

### ISSUE THREAD

**Issue by nebulahh** [rohitagr0310/Bookflow-app#281]
the header title of the login page should be the name of the app, not "authentication" and there should be no back button there. 

the login button will be conditionally rendered and an header should be added to the reset password page too. 

In addition, the logo at the footer should link to the home page

**Comment by nebulahh** [comment]
i would like to be assigned the task if it is valid. i have a working solution

**Comment by rohitagr0310** [comment]
@nebulahh 
the back button is a good feature, let it be. other than that, I believe the proposed changes are going to be a great addition to the website

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @nebulahh  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
