### ISSUE TITLE
Unable to setup the project because of dependencies version issue.

### ISSUE THREAD

**Issue by mahesha1150** [rohitagr0310/Bookflow-app#283]
When executing the command npm install, I am facing issues with respect to below dependencies.

"@material-ui/core": "^4.12.4",
"@mui/icons-material": "^5.14.8",
"@mui/material": "^5.14.8",
"@mui/styles": "^5.14.5",
	
"react-qr-reader": "^3.0.0-beta-1",

![image](https://github.com/rohitagr0310/Bookflow-app/assets/72247368/376079e7-2273-4e6c-801d-b00b17692740)

**Comment by nebulahh** [comment]
you are supposed to use `yarn install`. So make sure you have yarn installed on your computer

**Comment by mahesha1150** [comment]
Thanks.

**Comment by mahesha1150** [comment]
Thanks for the update. I was able to do yarn install and yarn start.
When I am trying to SignUp. I am facing the below issue. We do not have backend code to test this issue?
![image](https://github.com/rohitagr0310/Bookflow-app/assets/72247368/2dc91025-33c8-4787-9559-719a9d553986)

And you can see there is no proper error message at the top right as well.
