### ISSUE TITLE
BookFlow-app Test

### ISSUE THREAD

**Issue by dineshrajdhanapathyDD** [rohitagr0310/Bookflow-app#285]
I've identified a link issue in this project 
About us, page -> marketing manager Instagram link is missing. I have inspected the page and pasted the image below
Sign up page -> enter all details It shows some error red marks on the right corner of the signup page.
Reset password page -> It accepts new email addresses (not signup mail or sign-in mail)  enter the next page directly to the rest password page and cannot find the back button. 

![market manager insta link miss](https://github.com/rohitagr0310/Bookflow-app/assets/52989362/ad2bf429-5f8d-4237-bee4-284199bcd895)

![enter all details shown error right corner](https://github.com/rohitagr0310/Bookflow-app/assets/52989362/3f63c382-82c7-42fd-b33a-c86f7291ff5e)

![no back button](https://github.com/rohitagr0310/Bookflow-app/assets/52989362/df291ebf-ebd4-4cc4-a4d2-a10afb0bc6e1)

I believe that addressing this issue will further improve the project, and I'm willing to contribute to this project. I look forward to working with the community to tackle this challenge together.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @dineshrajdhanapathyDD 

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by dineshrajdhanapathyDD** [comment]
Thanks...
