### ISSUE TITLE
Improvement in UI in student panel

### ISSUE THREAD

**Issue by Adimaniac31** [rohitagr0310/Bookflow-app#286]
Hey, I would like to improve the UI of homepage I would like to add some animations and change some font-color and font-style. It would be nice if you could assign this issue to me.

**Comment by rohitagr0310** [comment]
@Adimaniac31 
we belive the ui for homepage is already good and we do not wish to bring any changes in it. if you wish to improve the UI, can you help in the admin panel and student panel.

they can be accessed by the adding `/student` and `/admin` in the base url

**Comment by Adimaniac31** [comment]
Yeah, sure I can work on that

**Comment by Adimaniac31** [comment]
Okay thanks, can you assign me this issue?

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Adimaniac31  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by rohitagr0310** [comment]
can you also specify which panel you wish to work upon

**Comment by Adimaniac31** [comment]
Sure, I will be working on student panel.

**Comment by rohitagr0310** [comment]
Great

**Comment by Adimaniac31** [comment]
Hii @jain-anshika  @rohitagr0310  I have created a PR can you look into it I have changed UI in student issued and thinking of keeping similar UI in other routes too. Feel free to give feedback.
