### ISSUE TITLE
Improvement in UI in admin panel

### ISSUE THREAD

**Issue by roxoho** [rohitagr0310/Bookflow-app#287]
Hi, I think changing favicon to match this project would be good.

I am willing to do this task.

**Comment by rohitagr0310** [comment]
there is already someone working on the favicon,
#244

**Comment by rohitagr0310** [comment]
but if you wish to help, can you Improve in UI in admin panel

it can be accessed by adding `/admin` on the base url

**Comment by roxoho** [comment]
OK, Yes I would like to help improve UI in admin panel.

Can you give me some info about how it should look, what it should contain, or anything else that would help me get started on this issue.

**Comment by rohitagr0310** [comment]
> OK, Yes I would like to help improve UI in admin panel.
> 
> Can you give me some info about how it should look, what it should contain, or anything else that would help me get started on this issue.

@roxoho 
i don't have any particular changes or designs in my mind as of particular moment but the mobile responsiveness for the page is not looking good. if you could help in that, that would be great

**Comment by roxoho** [comment]
ok, I will try

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @roxoho 

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by roxoho** [comment]
Great

**Comment by roxoho** [comment]
Hey, I think I lack the skill to do this task currently.

Sorry for the inconvenience, I am closing this issue.
