### ISSUE TITLE
When I am trying to SignUp. I am facing an error. With no error message at the top right.

### ISSUE THREAD

**Issue by mahesha1150** [rohitagr0310/Bookflow-app#293]
Thanks for the update. I was able to do yarn install and yarn start.
When I am trying to SignUp. I am facing the below issue. We do not have backend code to test this issue?
![image](https://github.com/rohitagr0310/Bookflow-app/assets/72247368/2dc91025-33c8-4787-9559-719a9d553986)

And you can see there is no proper error message at the top right as well.

_Originally posted by @mahesha1150 in https://github.com/rohitagr0310/Bookflow-app/issues/283#issuecomment-1755430695_

**Comment by mahesha1150** [comment]
As part of this repo, Main contributions are related to UI?

**Comment by rohitagr0310** [comment]
the issue is with relation to backend, the backend is written in netlify functions, which does not load up with `yarn start`

you would have to install netlify cli package to run the backend, which is defined inside the functions folder

**Comment by rohitagr0310** [comment]
@mahesha1150 
you can access the inner routes by adding `/admin` and `/student` to the base URL.

if you wish to contribute, can you help within the student panel or admin panel as they are still in development

**Comment by mahesha1150** [comment]
Sure Rohit. I was trying to setup the application and trying to signup. If contributions are needed on UI with /admin or /student. Please let me know where I can contribute.

**Comment by rohitagr0310** [comment]
@mahesha1150 
As the panels are still in development phase, the mobile responsiveness and overall ui is still lacking.

If you can improve the ui in any way while following the home page style, it would be very helpful

**Comment by rohitagr0310** [comment]
@mahesha1150 @shimmer12
please create a new issue with the task you wish to work upon 
thank you
