### ISSUE TITLE
Update in Contact Us page

### ISSUE THREAD

**Issue by vinayakjaas** [rohitagr0310/Bookflow-app#299]
### There is some problem in margin and padding I want to correct it please assign this issue to me 
![image](https://github.com/rohitagr0310/Bookflow-app/assets/96948435/9bfde720-5ebd-410b-877c-733c52d5ce7f)

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @vinayakjaas 

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by vinayakjaas** [comment]
@rohitagr0310  @jain-anshika  please review my pr
