### ISSUE TITLE
Header components restructure

### ISSUE THREAD

**Issue by qaidjoharj53** [rohitagr0310/Bookflow-app#302]

**Comment by Shashankpantiitbhilai** [comment]
i am interested

**Comment by rohitagr0310** [comment]
@Shashankpantiitbhilai, the header component is being rendered on the `Meet the team` page but is still not on the Contact Us and Terms and Conditions pages. I would love it if you could work on that

**Comment by SuyashRajput** [comment]
@rohitagr0310
And the links on the header are not react "Link" elements they are simple "a" elements
This cause the page to refresh multiple times
Mostly React Projects are made to be a single page applications.
I can work on this issue

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @SuyashRajput.

Work on a new branch with the feature as the branch name.

When you create a pull request, request a review from @rohitagr0310, @jain-anshika or, @qaidjoharj53

**Comment by SuyashRajput** [comment]
@rohitagr0310 you want the header and footer on every page right?

**Comment by rohitagr0310** [comment]
@SuyashRajput yes
