### ISSUE TITLE
Improvement in UI for Student panel

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#303]
the ui of the student panel is outdated. we want to improve it and match the theme of the new home page

the student panel can be accessed by adding `/student` to the base url

**Comment by Kabiirk** [comment]
Hi Rohit, let me know if it is fine with you that I work on 2 issues in this repo. If so, would appreciate if this could be assigned to me.

**Comment by rohitagr0310** [comment]
there is no issue with you or anyone working on multiple issues. it is a festival of collaboration after all

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Kabiirk .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by Kabiirk** [comment]
Thanks !

**Comment by rohitagr0310** [comment]
@Kabiirk 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.

**Comment by Kabiirk** [comment]
Hi Rohit,

Sorry for the delayed response, there were some issues with my ```yarn``` package manager that took time in resolving.

I am finishing up the ```student``` page (```Dashboard```, ```Account```, ```Requests``` etc.) & will move to ```/admin``` soon. Let me know if below UI improvement works for you:
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/469072df-24ec-442f-9ea6-5f144b8dbe74)

![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/b5b5e592-08e6-4e14-8877-4ffe2cb60d8b)

**Comment by Kabiirk** [comment]
Hi @rohitagr0310 , @jain-anshika , @qaidjoharj53 ,

Have made PR #339 for this. Let me know your thoughts on the improved designs !

best regards,
Kabiir
