### ISSUE TITLE
Improvement in UI for Admin panel

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#304]
the ui of the Admin panel is outdated. we want to improve it and match the theme of the new home page

the student panel can be accessed by adding `/admin` to the base url

**Comment by Kabiirk** [comment]
Hi Rohit, Can I work on this ?

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Kabiirk .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by rohitagr0310** [comment]
@Kabiirk 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.

**Comment by Kabiirk** [comment]
Hi @rohitagr0310 ,

I've completed improving UI for Admin Panel, it looks as follows:
1. **Dashboard** 
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/af62ffb9-92c1-4ef3-8924-2e4507cb0ff2)

2. **Add Book**
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/a78a5ef8-0b0f-4be4-a367-15052b2cf5ec)

3. **All Books**
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/39e5e1b5-fb87-4955-9973-4c514ccb7075)

4. **Pending Issue**
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/ee33901f-0013-4565-adc5-abf93f99368f)

5. **Issued Books**
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/3f3028ea-3cdd-4fa3-b51e-4e6f30fdbc86)

6. **Manage Students** (Have also created Base Card UI for this, someone else can populate this as per required logic)
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/33344152-9fcb-4fad-a432-42927d828483)

7. **History**
![image](https://github.com/rohitagr0310/Bookflow-app/assets/16386226/bacb1ab0-e822-43e0-bd64-4afd33d252c9)


Let me know if this is fine & I can move forward with the PR.

**Comment by rohitagr0310** [comment]
Looks great 👍
