### ISSUE TITLE
Improvement in UI Mobile Responsiveness for Student panel

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#305]

**Comment by nayakswadhin** [comment]
@rohitagr0310 Can you please assign me this issue? I would love to work in it.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @nayakswadhin .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by nayakswadhin** [comment]
@rohitagr0310 Can we add tailwind CSS in this project or we have to stick to vanilla CSS??

**Comment by rohitagr0310** [comment]
i personally do not have much experience with tailwind CSS, would adding tailwind CSS in one component interfere with other components, if not then we can use tailwind CSS

i had always been thinking about working with tailwind css

**Comment by rohitagr0310** [comment]
@nayakswadhin 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.
