### ISSUE TITLE
Improvement in UI Mobile Responsiveness for Admin panel

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#306]

**Comment by Shashankpantiitbhilai** [comment]
i am interested

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Shashankpantiitbhilai .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by rohitagr0310** [comment]
@Shashankpantiitbhilai 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.
