### ISSUE TITLE
Improvement of Menu bar in Admin panel

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#308]
the Menu Bar of the student panel is outdated. we want to improve it and match the theme of the new home page

the student panel can be accessed by adding `/admin` to the base url

**Comment by Shashankpantiitbhilai** [comment]
I am intereseted please assign this to me

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Shashankpantiitbhilai  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by rohitagr0310** [comment]
@Shashankpantiitbhilai 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.
