### ISSUE TITLE
[BUG] UI of the contact us page is not responsive for mobile 

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#310]
### What happened?

when you open the Contact Us page on mobile, the component with name and phone number goes out the boundary of the page

### How can we reproduce this bug?

open the Contact Us page on the mobile

### Desktop Information (Optional)

windows 10
latest react and npm

### Urgency (Optional)

Low priority

**Comment by PCoder23** [comment]
Assign this to me please

**Comment by Dkingofcode** [comment]
Can i be assigned this issue?

**Comment by rohitagr0310** [comment]
@Dkingofcode 
Since @PCoder23 was first to create a pull request, I will assign the issue to him
