### ISSUE TITLE
[Horizontal Scroll-Bar] 

### ISSUE THREAD

**Issue by Ayusht777** [rohitagr0310/Bookflow-app#312]
### What happened?

hey their is Horizontal scrolling bar issue on your website

### How can we reproduce this bug?

Css Padding or Margin May can cause it 
![Screenshot (267)](https://github.com/rohitagr0310/Bookflow-app/assets/106388215/f441bd68-8548-4f8c-bf41-892d4aeb198f)

### Urgency (Optional)

Medium priority

**Comment by PCoder23** [comment]
Please assign this issue to me

**Comment by Ayusht777** [comment]
i am just a contributer  not the maintainer

**Comment by PCoder23** [comment]
oh ok, btw it should be horizontal bar i guess
