### ISSUE TITLE
[Footer & Contact page layout issues] 

### ISSUE THREAD

**Issue by ricgomez99** [rohitagr0310/Bookflow-app#314]
### What happened?

I found some issues related to the footer component and the Contact page. The first one (footer), is about an extra element that's been generated under the "App" div element, and it's generating an extra space at the bottom of the page. It is visible on every screen size and every page of the website. The second one (Contact Page) is about the page's navbar, which is not available or visible on that page, and makes it hard to return to the previous page or other section of the website. Please let me know if someone is already working on this issue, or if you need help with it, I'll be more than happy to give a hand. 

<img width="528" alt="layout-issuesPNG" src="https://github.com/rohitagr0310/Bookflow-app/assets/79469076/5ebc1394-0525-42f8-856f-cd0d8932d8db">

<img width="298" alt="layout-issues-2" src="https://github.com/rohitagr0310/Bookflow-app/assets/79469076/f207734a-de49-400d-8a28-00d39f7cd3d1">

### How can we reproduce this bug?

Take a look at the browser's developer tools. 

### Urgency (Optional)

None

**Comment by rohitagr0310** [comment]
@ricgomez99 
the nav bar bug is already been worked upon by someone in another issue

the bug with the extra space under footer is not something being worked upon. since you brought the bug to attention, I will assign the issue to you

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @ricgomez99 .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by ricgomez99** [comment]
Hi @rohitagr0310! Sounds good, I'll be working on it.

**Comment by ricgomez99** [comment]
**Hey Guys,**

I've made some updates to the project and I would appreciate your feedback before creating a pull request.

**Main Changes:**
1. **Blank Space Issue:** I've removed the extra space at the bottom of the contact page.

<img width="651" alt="contact-layout-fixed" src="https://github.com/rohitagr0310/Bookflow-app/assets/79469076/228ecd40-6a5d-419a-9ee3-1c8df16105fb">

2. **Layout Improvements:** I've enhanced the layout for both desktop and mobile views.

<img width="227" alt="Contact-layout-fixed2" src="https://github.com/rohitagr0310/Bookflow-app/assets/79469076/f5957138-bcd0-4f41-8b5c-7910a944d14a"> 

Please share your thoughts and suggestions. Your input is valuable to me.

Thank you!

**Comment by rohitagr0310** [comment]
- Layout for the mobile screen looks great
- Extra space is removed. The page looks more centralized and smooth

when you create a pull request, I will be able to see a build preview.

**Comment by ricgomez99** [comment]
Okay! I'll do it right away
