### ISSUE TITLE
Title:  Add hover effect to know more button in landing page.

### ISSUE THREAD

**Issue by lunoos** [rohitagr0310/Bookflow-app#316]
### Is your feature request related to a problem? Please describe.

On the landing page of the application, the Know More button does not have any hover effect as the menu button in nav bar.

### Describe the solution you'd like.

I would like to add the hover effect to the 'Know more' button similar to the the menu buttons in the nav bar to keep the application consistent.

### Describe alternatives you've considered.

Need to add the hover effect to 'Know more' button if we need to keep the application UX consistent.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/rohitagr0310/Bookflow-app/assets/65530077/6953d3b4-6557-483f-83e8-60b54c8a1371)

If change is requred please assign it to me with hackoctoberfest tag.

Thanks.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @lunoos .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
