### ISSUE TITLE
Title: Add a contributors section in the README.md

### ISSUE THREAD

**Issue by rohitagr0310** [rohitagr0310/Bookflow-app#317]
### Explain what you want to add/change in documentation.

add a section at the bottom of the readme showcasing the contributors of the project by showing them in icon form

**Comment by nayakswadhin** [comment]
I would love to this task. Can you assign this issue to me?

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @nayakswadhin .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by nayakswadhin** [comment]
@rohitagr0310 I have created a PR on this issue. Kindly review it.
