### ISSUE TITLE
Improper favicon icon 

### ISSUE THREAD

**Issue by vashukashyap** [rohitagr0310/Bookflow-app#318]
### What happened?

The favicon icon of the website contain react app favicon icon. it should have the website logo

### How can we reproduce this bug?

- open the website
- near the title of the website you can see the website's favicon icon.

### Urgency (Optional)

None

**Comment by vashukashyap** [comment]
can i work on this issue?

**Comment by rohitagr0310** [comment]
@vashukashyap 
how do you suggest to improve the favicon for the website

**Comment by vashukashyap** [comment]
@rohitagr0310 
sir, the favicon icon of the website should describe what about website is! and sometime it attract people and make look website authentic,  if you want i can design a good favicon for the website.. and you verify which, you to put on the website.

**Comment by rohitagr0310** [comment]
it's great to see your enthusiasm for improving our website's favicon! Favicon design is an important aspect of branding and user experience, so your offer is much appreciated.

 I'd like to thank you for your willingness to contribute to our open-source project.
