### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Abh1noob** [rohitagr0310/Bookflow-app#319]
### What happened?

Issue 1: Login Alignment not proper
Issue 2: No smooth scroll in "Know More" button link
Issue 3: Clicking BookFlow button in Navbar should scroll to top, not working
<img width="1440" alt="image" src="https://github.com/rohitagr0310/Bookflow-app/assets/56132559/14adf77f-e2d2-4286-a5f8-fef9e7555d24">

Issue 4: Switch button has wierd scroll behaviour.
<img width="1440" alt="image" src="https://github.com/rohitagr0310/Bookflow-app/assets/56132559/e7c82792-d81c-47ee-868d-cf5b699e26d2">

Issue 5: Terms and condition title hidden under NAVBAR
<img width="1440" alt="image" src="https://github.com/rohitagr0310/Bookflow-app/assets/56132559/12b8cccb-1c69-40d1-982a-e3abbfb6c7a7">

### How can we reproduce this bug?
Issue 1,2,3:
Can see in home page

Issue 4:
Can see in Login Screen

Issue 5: 
Can see after clicking "Terms"

### Urgency (Optional)

None

**Comment by rohitagr0310** [comment]
@Abh1noob 
are you willing to work on so many issues by yourself

**Comment by Abh1noob** [comment]
Ya, I dont mind. Assign me (Also label it hacktober)
