### ISSUE TITLE
The contact page form stocked inside the header

### ISSUE THREAD

**Issue by aliveevie** [rohitagr0310/Bookflow-app#326]
There should be a margin between the header and the contact page to make look more professional

**Comment by rohitagr0310** [comment]
i have commented on your pr. please check it out

**Comment by kivenalaric** [comment]
Good morning. I am new to open source and i wish to participate on any issues or bugs available, @rohitagr0310  i would be happy to help with anything.

**Comment by rohitagr0310** [comment]
Good morning, @kivenalaric! Welcome to the open-source community, and thank you for your willingness to contribute. We're excited to have you on board!

You can start by taking a look at our repository's list of open issues. Feel free to browse through them, and if you find something that piques your interest or aligns with your skills, please don't hesitate to comment on the issue or create a new one if you have a particular bug or feature in mind.

If you have any questions or need assistance with anything, don't hesitate to reach out. We're here to help and guide you as you get started with your open-source journey. Once again, welcome, and we appreciate your enthusiasm to contribute to our project! 😊🚀

**Comment by kivenalaric** [comment]
Okay thank you sir. I'll go through.

**Comment by rohitagr0310** [comment]
@aliveevie 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.
