### ISSUE TITLE
Update TwitterIcon

### ISSUE THREAD

**Issue by Divjot02** [rohitagr0310/Bookflow-app#330]
### Description
The current TwitterIcon at the bottom of the homepage is the old Twitter logo. We should consider updating this icon to the new Twitter logo to maintain a modern and consistent visual identity.

 **Current Logo**
![IMG_20231021_032833](https://github.com/rohitagr0310/Bookflow-app/assets/140320635/c85dc21b-684d-471d-ab19-a347f27b7a58)

**Proposed Solution :** Update the import statement to import new logo of Twitter

**Comment by Divjot02** [comment]
Hello @rohitagr0310, if there is a need for this update, I would appreciate it if you could assign it to me. I am open to any suggestions or guidance you may have.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Divjot02 .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
