### ISSUE TITLE
Title: Add Animations with framer-motion for Better User Experience

### ISSUE THREAD

**Issue by M-A-N-I-K** [rohitagr0310/Bookflow-app#331]
### Is your feature request related to a problem? Please describe.

As our web project continues to evolve, we recognize the importance of providing a visually engaging and interactive user experience. Currently, our project lacks animations, which can make the user interface feel static and less captivating.

### Describe the solution you'd like.

We propose introducing animations using the framer-motion library to improve the overall user experience on our web application. These animations will not only make the interface more visually appealing but also enhance user engagement and interaction.

### Describe alternatives you've considered.

Benefits:

-     Enhanced User Engagement: Engaging animations can capture users' attention, guiding them through the user interface and making our application more interactive.
-     Improved Aesthetics: Animations can add a modern and dynamic touch to our project, making it more visually appealing.
-     Interactive Feedback: Animations can provide feedback to users, making interactions more intuitive.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @M-A-N-I-K .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by rohitagr0310** [comment]
@M-A-N-I-K 
The issue has been inactive for an extended period. I am reaching out to notify you that if it remains inactive by the end of this month, we will proceed to close this issue.
