### ISSUE TITLE
Enhance User Experience with Background Images

### ISSUE THREAD

**Issue by M-A-N-I-K** [rohitagr0310/Bookflow-app#332]
### Is your feature request related to a problem? Please describe.

While our web project offers valuable content and functionality, the current use of white backgrounds throughout the application gives it a somewhat plain and uninviting appearance. To create a more engaging and visually appealing user experience, we should consider introducing background images to certain sections of the application.

### Describe the solution you'd like.

We propose adding background images to select sections of our web application to improve the aesthetics and make it more visually engaging. Background images can set the mood, convey our brand's personality, and provide a better sense of context to users.

### Describe alternatives you've considered.

Benefits:

    Enhanced Aesthetics: Background images can add depth and visual appeal to our project, making it more attractive to users.
    Brand Identity: Carefully chosen images can help convey our brand's identity and values.
    Improved User Engagement: A visually engaging interface can keep users on our site longer, potentially leading to increased engagement.

**Comment by rohitagr0310** [comment]
how do you propose to do this

**Comment by kivenalaric** [comment]
> how do you propose to do this

i did something about this on the home page but getting the right image choice is my problem so i got variants of what i did, you can suggest other images or still reject.
![2023-10-24 (4)](https://github.com/rohitagr0310/Bookflow-app/assets/89359876/612be7cd-7029-405c-8e21-c1bd85a57ba6)
![2023-10-24 (6)](https://github.com/rohitagr0310/Bookflow-app/assets/89359876/36ebe045-7ea3-4182-a30b-977d3eb832c0)

![2023-10-24 (5)](https://github.com/rohitagr0310/Bookflow-app/assets/89359876/98f3ef0b-1332-40cf-acde-c8e2e8196955)

**Comment by rohitagr0310** [comment]
@kivenalaric 
the second variant looks good. please proceed with that one

**Comment by kivenalaric** [comment]
> @kivenalaric the second variant looks good. please proceed with that one

can you give me access to push sir, tried pushing and permission was denied.

**Comment by rohitagr0310** [comment]
@kivenalaric 
Are you working on a new fork because in fork, there is no need for permission

Only if you are working in the main repo and in main branch will it restrict you from pushing

**Comment by kivenalaric** [comment]
Let me fork again because i forked it

**Comment by kivenalaric** [comment]
Done review required @rohitagr0310
