### ISSUE TITLE
Navbar is not properly responsive

### ISSUE THREAD

**Issue by Sreyasree-001** [rohitagr0310/Bookflow-app#333]
### What happened?

Navigation bar is not properly visible in other devices

### How can we reproduce this bug?

Navbar is not visible in mobile view

### Urgency (Optional)

None

**Comment by rohitagr0310** [comment]
#334

**Comment by Malvericus** [comment]
Hey, when I inspect the website, the Navbar shows to be responsive for mobile screens as well:

<img width="1467" alt="Screenshot 2023-10-22 at 11 48 34 PM" src="https://github.com/rohitagr0310/Bookflow-app/assets/135830024/74cdf868-05e6-4fa6-87bd-d74faa728f71">
<img width="1467" alt="Screenshot 2023-10-22 at 11 48 42 PM" src="https://github.com/rohitagr0310/Bookflow-app/assets/135830024/0258d24f-c32c-4394-a5a7-794678b7b961">
