### ISSUE TITLE
Login form items not well aligned.

### ISSUE THREAD

**Issue by kivenalaric** [rohitagr0310/Bookflow-app#338]
### What happened?

navigated to the login page and saw the input labels interfering with the form, they are kind of joined together and its bad.[](url)

### How can we reproduce this bug?

Navigate to the login page and see the form its not good.

### Urgency (Optional)

None

**Comment by kivenalaric** [comment]
im ready to fix this.
![2023-10-24](https://github.com/rohitagr0310/Bookflow-app/assets/89359876/e1b01bee-e470-4eb0-b6bf-04a6f514c39a)

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @kivenalaric .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by kivenalaric** [comment]
> @jain-anshika

Done please review @rohitagr0310 
PR created
