### ISSUE TITLE
Title: Create FAQ Page

### ISSUE THREAD

**Issue by rishiofficial** [rohitagr0310/Bookflow-app#344]
### Is your feature request related to a problem? Please describe.

We need to create a Frequently Asked Questions (FAQ) page to provide answers to common user queries on our website. The FAQ page will enhance user experience by offering quick access to information.

### Describe the solution you'd like.

Design the FAQ page layout.
Write and format FAQ questions and answers.
 Add navigation and links to the FAQ page in the website's menu.
 Test the page across different devices and browsers for responsiveness.
 Ensure the content is up to date and accurate.
 Style the FAQ page for a user-friendly experience.

### Describe alternatives you've considered.

The FAQ page will serve as a valuable resource for users, providing answers to common inquiries, which can help reduce support requests. It's important to make sure the content is easily accessible, well-organized, and visually appealing.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @rishiofficial .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
